# ????????? ??????????? ? PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/online_course_db
spring.datasource.username=postgres
spring.datasource.password=Bb290606

# ????? Hibernate ??? ???????? ??????? ?? ?????? ????? ??????? Bekarys...
# ????: spring.jpa.hibernate.ddl-auto=update
# ?????? ???:
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ????
server.port=8080